### ISSUE TITLE
`espanso_gui` roadmap

### ISSUE THREAD

**Issue by AucaCoyan** [Pebkac03/espanso_gui#2]
Hello there!
Now that we have a GUI project here. We need some structure to keep moving forward.
As we work in issues and features, we can edit the list. These are not in order! This is a all you can eat list of features

# ❗ TODO
- [ ] missing builds in `macOS` and `Linux` operative systems
- [ ] add option to select the config path, either as a config file or as a GUI option (whichever is better!)
- [ ] add some basic CI
- [ ] add some basic testing
- [ ] `CONTRIBUTING` guide
- [ ] adjust `README.md`
    - [ ] add the supported espanso version
    - [ ] add badges

# ✅ Done: 
- [x] ready items are here!

for reference, this issue is based in [the roadmap of `nufmt`](https://github.com/nushell/nufmt/issues/11)
